version: '3.0'
services:
  app:
    build: .
    volumes:
      - ./src:/workdir/src
      - ./output:/workdir/output
      - ./config:/workdir/config
    environment:
      PYTHONPATH: "/workdir"
      PYTHONUNBUFFERED: "1"
